mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views
from coffee_app import views as appointment_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('coffee/', include('coffee_app.urls')),
    path('store/', include('store.urls')),

    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('cart/', views.CartView.as_view(), name='CartView'),
    path('checkout/', views.CheckOutView.as_view(), name='CheckOutView'),
    path('my-orders/', views.MyOrders.as_view(), name='MyOrders'),
    path('all-orders/', views.AllOrdersView.as_view(), name='AllOrdersView'),
]

coffee_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.shortcuts import redirect
import datetime

# Create your models here.

WEEK_DAYS = (
    (1, 'Monday'),
    (2, 'Tuesday'),
    (3, 'Wednesday'),
    (4, 'Thursday'),
    (5, 'Friday'),
    (6, 'Saturday'),
    (7, 'Sunday'),
)

class WeekDays(models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name

class CoffeeType(models.Model):
    name = models.CharField(max_length=50)

    @staticmethod
    def get_all_coffee_type():
        return CoffeeType.objects.all()

    def __str__(self):
        return self.name

class TableType(models.Model):
    name = models.CharField(max_length=50)
    days_available = models.ManyToManyField(WeekDays, related_name="available_table_types")

class Table(models.Model):
    LOCATION_CHOICES=(
        ('out', 'Outside'),
        ('in', 'Inside'),
    )
    location = models.CharField(choices=LOCATION_CHOICES, max_length=5, default='out')
    capacity = models.IntegerField(default=0)
    day = models.CharField(null=True, blank=True, default=None, max_length=100)
    booking_time = models.CharField(null=True, blank=True, default=None, max_length=100)
    booked_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="tables_booked", blank=True, null=True)
    booked = models.BooleanField(default=False)

class Coffee(models.Model):
    STATUS_CHOICES=(
        ('in_s', 'In stock'),
        ('out_s', 'Out of stock'),
    )
    name = models.CharField(max_length=60)
    price = models.IntegerField(default=0)
    image = models.ImageField(upload_to='uploads/coffee/')
    age_limit = models.BooleanField(default=False)
    days_available = models.ManyToManyField(WeekDays, related_name="available_coffees")
    available_from = models.TimeField(auto_now_add=False, blank=True, null=True, default=None)
    available_to = models.TimeField(auto_now_add=False, blank=True, null=True, default=None)
    type = models.ForeignKey(CoffeeType, on_delete=models.CASCADE, default=1)
    description = models.TextField(blank=True, null=True)
    status = models.CharField(choices=STATUS_CHOICES, max_length=50, default='in_s')
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    @staticmethod
    def get_coffee_by_id(ids):
        return Coffee.objects.filter(id__in=ids)

    @staticmethod
    def get_all_coffee():
        return Coffee.objects.all()
  
    @staticmethod
    def get_all_coffee_by_category(category):
        return Coffee.objects.filter(category__name=category)

    @property
    def get_exerpt(self):
        try:
            return self.description[:50]
        except:
            return None

    @property
    def get_image_url(self):
        try:
            return self.image.url
        except:
            return ''

    @property
    def get_absolute_url(self):
        return f"{reverse('CoffeeDetailView', kwargs={'id':self.id})}"


class OrderItem(models.Model):
    item = models.ForeignKey(Coffee, on_delete=models.CASCADE, related_name="order_items")
    price = models.IntegerField(default=0)
    quantity = models.IntegerField(default=1)
    date = models.DateTimeField(auto_now_add=True)

    @staticmethod
    def get_order_item_by_id(ids):
        return OrderItem.objects.filter(product__id__in = ids)


class Order(models.Model):
    STATUS_CHOICES=(
        ('p', 'Order Placed'),
        ('c', 'Completed'),
    )
    customer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="orders")
    items = models.ManyToManyField(OrderItem, related_name="orders")
    price = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(choices=STATUS_CHOICES, max_length=50, default='p')

    @staticmethod
    def get_orders_by_customer(customer_id):
        return OrderItem.objects.filter(customer=customer_id).order_by('-date')

store/models.py
from django.db import models

# Create your models here.

store/views.py
import json
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import View
from coffee_app.models import Coffee, Order, OrderItem
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

from users.decorators import allowed_users

# Create your views here.

class CartView(View):
    def get(self, request):
        cart = request.session.get("cart", {})
        if not cart:
            request.session["cart"] = {}
        data = []
        total_price = 0
        if cart:
            products = Coffee.get_coffee_by_id(cart.keys())
            for product in products:
                quantity = cart.get(str(product.id), None)
                if quantity:
                    product_total = product.price * int(quantity)
                    data.append({
                        "product": product,
                        "quantity": quantity,
                        "total_price": product_total
                    })
                    total_price += product_total
        context = {"data": data, "total_price": total_price}
        return render(request, "store/cart.html", context)

    def post(self, request):
        product_id = request.POST.get('product_id', None)
        action = request.POST.get('action', None)
        cart = request.session.get('cart', {})
        if not cart:
            cart = request.session["cart"] = {}

        quantity = cart.get(product_id, None)

        if quantity:
            if action == "remove":
                if quantity <= 1:
                    cart.pop(product_id)
                    messages.success(request, "Item Removed")
                else:
                    cart[product_id] = quantity-1
                    messages.success(request, "Quantity Decreased")
            elif action == "add":
                cart[product_id] = quantity+1
                messages.success(request, "Quantity Increased")
            elif action == "delete":
                cart.pop(product_id)
                messages.success(request, "Item Removed")
        else:
            cart[product_id] = 1
            messages.success(request, "Added to cart successfully.")

        request.session['cart'] = cart
        
        print('cart', request.session['cart'])
        previous_url = request.META['HTTP_REFERER'] 
        if previous_url:
            return redirect(previous_url)
        return redirect('store:HomeView')

class AllOrdersView(View):
    @allowed_users(allowed_roles=["bariast"])
    def get(self, request):
        try:
            orders = request.user.orders.all().order_by("-date")
        except:
            orders = None
        context = {"orders": orders}
        return render(request, "store/list-all-orders.html", context)


class MyOrders(View):
    def get(self, request):
        try:
            orders = request.user.orders.all().order_by("-date")
        except:
            orders = None
        context = {"orders": orders}
        return render(request, "store/my-orders.html", context)


@method_decorator(csrf_exempt,  name='dispatch')
class CheckOutView(View):
    def post(self, request):
        user = request.user
        cart = request.session.get("cart", {})
        order_items = []
        total_price = 0
        products = Coffee.get_coffee_by_id(cart.keys())
        for product in products:
            quantity = cart.get(str(product.id), None)
            if quantity:
                product_total = product.price * int(quantity)
                order_item = OrderItem.objects.create(
                    item = product,
                    price = product_total,
                    quantity = quantity,
                )
                order_items.append(order_item)
                total_price += product_total
        order = Order.objects.create(
            customer = user,
            price = total_price,
            status = 'c',
        )
        for item in order_items:
            order.items.add(item)
        request.session["cart"] = None
        return HttpResponse(status=200)

templates/store/cart.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block ExtraCss %}

<style>
    .ui-w-40 {
        width: 100px !important;
        height: auto;
    }
    
    .card{
        box-shadow: 0 1px 15px 1px rgba(52,40,104,.08);    
    }
    
    .ui-product-color {
        display: inline-block;
        overflow: hidden;
        margin: .144em;
        width: .875rem;
        height: .875rem;
        border-radius: 10rem;
        -webkit-box-shadow: 0 0 0 1px rgba(0,0,0,0.15) inset;
        box-shadow: 0 0 0 1px rgba(0,0,0,0.15) inset;
        vertical-align: middle;
    }
</style>

{% endblock ExtraCss %}

{% block content %}

{% block header %}{% endblock header %}

<div class="row my-4">
    <div class="col-9">
        <div class="card">
            <div class="card-header">
                <h2>Shopping Cart</h2>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered m-0">
                    <thead>
                        <tr>
                        <!-- Set columns width -->
                        <th class="text-center py-3 px-4" style="min-width: 200px;" >Coffee Name &amp; Details</th>
                        <th class="text-right py-3 px-4" style="width: 100px;">Price</th>
                        <th class="text-center py-3 px-4" style="width: 120px;">Quantity</th>
                        <th class="text-right py-3 px-4" style="width: 100px;">Total</th>
                        <th class="text-center align-middle py-3 px-0" style="width: 40px;">
                            <i class="fas fa-trash-alt"></i>
                        </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for entry in data %}
                        <tr>
                            <td class="p-3">
                                <div class="media align-items-center">
                                <img src="{{entry.product.get_image_url}}" class="d-block ui-w-40 ui-bordered mr-4 shadow-sm" alt="">
                                <div class="media-body">
                                    <a href="{{entry.product.get_absolute_url}}" class="d-block text-dark">{{entry.product.name}}</a>
                                </div>
                                </div>
                            </td>
                            <td class="text-right font-weight-semibold align-middle p-4">${{entry.product.price}}</td>
                            <td class="align-middle p-4">
                                {% comment %} <input type="text" class="form-control text-center" value="2"> {% endcomment %}
                                <div class="row">
                                    <div class="col-4">
                                        <form action="{% url 'CartView' %}" method="POST">
                                            {% csrf_token %}
                                            <input type="hidden" name="product_id" value="{{entry.product.id}}">
                                            <input type="hidden" name="action" value="remove">
                                            <input type="submit" class="btn_no_syle" value="-">
                                        </form>
                                    </div>
                                    <div class="col-4">
                                        <span>{{entry.quantity}}</span>
                                    </div>
                                    <div class="col-4">
                                        <form action="{% url 'CartView' %}" method="POST">
                                            {% csrf_token %}
                                            <input type="hidden" name="product_id" value="{{entry.product.id}}">
                                            <input type="hidden" name="action" value="add">
                                            <input type="submit" class="btn_no_syle" value="+">
                                        </form>
                                    </div>
                                </div>
    
                            </td>
                            <td class="text-right font-weight-semibold align-middle p-4">${{entry.total_price}}</td>
                            <td class="text-center align-middle px-0">
                                <form action="{% url 'CartView' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="product_id" value="{{entry.product.id}}">
                                    <input type="hidden" name="action" value="delete">
                                    <input type="submit" class="btn text-danger" value="x">
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
    
                    </tbody>
                    </table>
                </div>
                <!-- / Shopping cart table -->
            
                <div class="d-flex flex-wrap justify-content-between align-items-center pb-4">
                    <div class="d-flex ms-auto">
                    <div class="text-right mt-4">
                        <label class="text-muted font-weight-normal m-0">Total price</label>
                        <div class="text-large"><strong>${{total_price}}</strong></div>
                    </div>
                    </div>
                </div>
                <div class="float-right">
                    <a href="{% url 'HomeView' %}" class="btn btn-lg btn-default md-btn-flat mt-2 mr-3">Back to shopping</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-3">
        <div id="paypal-button-container"></div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://www.paypal.com/sdk/js?client-id=AaTLWqtnu2N0JYRhWyPoGjfUHRvtZxUtB0MOeiuF8w1GFBEhVvGDXsNlO5MSQDyN4-HzCleUzSWblHXR&currency=USD"></script>
<script>
    paypal.Buttons({

      // Sets up the transaction when a payment button is clicked
      createOrder: function(data, actions) {
        return actions.order.create({
          purchase_units: [{
            amount: {
              value: '{{total_price}}'
            }
          }]
        });
      },

      // Finalize the transaction after payer approval
      onApprove: function(data, actions) {
        return actions.order.capture().then(function(orderData) {
            // Successful capture! For dev/demo purposes:
            console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
            var transaction = orderData.purchase_units[0].payments.captures[0];
            console.log(transaction.status + ': ' + transaction.id)
            approvePayment()
            alert('Payment Completed Successfully ');
            // When ready to go live, remove the alert and show a success message within this page. For example:
            // var element = document.getElementById('paypal-button-container');
            // element.innerHTML = '';
            // element.innerHTML = '<h3>Thank you for your payment!</h3>';
            // Or go to another URL:  actions.redirect('thank_you.html');
        });
      }
    }).render('#paypal-button-container');

    function approvePayment(){
        $.ajax({
            url: "{% url 'CheckOutView' %}",
            dataType: "json",
            type: "Post",
            async: true,
            data: { },
            success: function (data) {
                console.log(data)
                window.location.href = "{% url 'HomeView' %}"
            },
            error: function (xhr, exception) {
                console.log(xhr, exception)
                window.location.href = "{% url 'HomeView' %}"
            }
        });
    }

</script>
{% endblock content %}

templates/store/list-all-booking.html
{% extends "base.html" %}
{% load custom_tags %}

{% block footer %}

    <section class="container">
        <h1 class="display-4 text-center mb-4">All Bookings</h1>
        <div class="row" style="max-height: 80vh; overflow-y: scroll;">
            <div class="col">
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Booked By</th>
                        <th scope="col">Location</th>
                        <th scope="col">Capacity</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for table in bookings %}
                        <tr>
                            <th scope="row">{{table.id}}</th>
                            <td>
                                <p>{{table.booked_by.username}}</p>
                            </td>
                            <td>
                                <p>{{table.get_location_display}}</p>
                            </td>
                            <td>
                                <p>{{table.capacity}}</p>
                            </td>
                            <td>
                                <form action="." method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" value="{{table.id}}" name="table_id">
                                    <input type="hidden" value="cancel" name="action">
                                    <button class="btn btn-warning btn-sm">Unbook</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>




{% endblock %}

templates/store/list-all-orders.html
{% extends "base.html" %}
{% load custom_tags %}

{% block footer %}

    <section class="container">
        <h1 class="display-4 text-center mb-4">All Orders</h1>
        <div class="row" style="max-height: 80vh; overflow-y: scroll;">
            <div class="col">
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Ordered At</th>
                        <th scope="col">User</th>
                        <th scope="col">Price</th>
                        <th scope="col">Items</th>
                        <th scope="col">Status</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for order in orders %}
                        <tr>
                            <th scope="row">{{order.date.date}}</th>
                            <td>
                                <p>{{order.customer.username}}</p>
                            </td>
                            <td>
                                <p>{{order.price}}</p>
                            </td>
                            <td>
                                {% for item in order.items.all %}
                                    <p>
                                        {{item.item.name}} ({{item.quantity}})
                                    </p>
                                {% endfor %}
                            </td>
                            <td>
                                {% if order.status %}
                                    <i class="fa fa-check text-success" aria-hidden="true"></i>
                                {% else %}
                                    <i class="fa fa-times text-danger" aria-hidden="true"></i>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>




{% endblock %}

templates/store/my-orders.html
{% extends "base.html" %}
{% load custom_tags %}

{% block footer %}

    <section class="container">
        <h1 class="display-4 text-center mb-4">My Orders</h1>
        <div class="row" style="max-height: 80vh; overflow-y: scroll;">
            <div class="col">
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Ordered At</th>
                        <th scope="col">Price</th>
                        <th scope="col">Items</th>
                        <th scope="col">Status</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for order in orders %}
                        <tr>
                            <th scope="row">{{order.date.date}}</th>
                            <td>
                                <p>{{order.price}}</p>
                            </td>
                            <td>
                                {% for item in order.items.all %}
                                    <p>
                                        {{item.item.name}} ({{item.quantity}})
                                    </p>
                                {% endfor %}
                            </td>
                            <td>
                                {% if order.status %}
                                    <i class="fa fa-check text-success" aria-hidden="true"></i>
                                {% else %}
                                    <i class="fa fa-times text-danger" aria-hidden="true"></i>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>




{% endblock %}

templates/store/store.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <script src="https://www.paypal.com/sdk/js?client-id=AfHssuQd-igtuQLQ9VZ73ju2aIcrxWPLv2JZZ7FDBYNzKdn6WX406ln46kIFw6ILZGBLzFL49kgDQOTC&currency=USD"></script>

    <div class="content-section">
      {% comment %} <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Payment</legend>
              {{ form|crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Pay</button>
          </div>
      </form> {% endcomment %}
      <div id="paypal-button-container"></div>
    </div>

    <script>
        paypal.Buttons({
  
          // Sets up the transaction when a payment button is clicked
          createOrder: function(data, actions) {
            return actions.order.create({
              purchase_units: [{
                amount: {
                  value: '77.44' // Can reference variables or functions. Example: `value: document.getElementById('...').value`
                }
              }]
            });
          },
  
          // Finalize the transaction after payer approval
          onApprove: function(data, actions) {
            return actions.order.capture().then(function(orderData) {
              // Successful capture! For dev/demo purposes:
                  console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                  var transaction = orderData.purchase_units[0].payments.captures[0];
                  alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');
  
              // When ready to go live, remove the alert and show a success message within this page. For example:
              // var element = document.getElementById('paypal-button-container');
              // element.innerHTML = '';
              // element.innerHTML = '<h3>Thank you for your payment!</h3>';
              // Or go to another URL:  actions.redirect('thank_you.html');
            });
          }
        }).render('#paypal-button-container');
  
      </script>
{% endblock content %}


<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- Ensures optimal rendering on mobile devices -->
  </head>

  <body>
    <!-- Include the PayPal JavaScript SDK; replace "test" with your own sandbox Business account app client ID -->
    <script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>

    <!-- Set up a container element for the button -->
    <div id="paypal-button-container"></div>

    <script>
      paypal.Buttons({

        // Sets up the transaction when a payment button is clicked
        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{
              amount: {
                value: '77.44' // Can reference variables or functions. Example: `value: document.getElementById('...').value`
              }
            }]
          });
        },

        // Finalize the transaction after payer approval
        onApprove: function(data, actions) {
          return actions.order.capture().then(function(orderData) {
            // Successful capture! For dev/demo purposes:
                console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                var transaction = orderData.purchase_units[0].payments.captures[0];
                alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');

            // When ready to go live, remove the alert and show a success message within this page. For example:
            // var element = document.getElementById('paypal-button-container');
            // element.innerHTML = '';
            // element.innerHTML = '<h3>Thank you for your payment!</h3>';
            // Or go to another URL:  actions.redirect('thank_you.html');
          });
        }
      }).render('#paypal-button-container');

    </script>
  </body>
</html>